version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - .docker/database.sql:/docker-entrypoint-initdb.d/init.sql
